### ISSUE TITLE
Ares library 1.0.6 is not working

### ISSUE THREAD

**Issue by DigitalSolutionsCZ** [h4kuna/object-wrapper#1]
Due to rename of CurlBuilder to CUrlBuilder the v1.0.6 is not working anymore... Huge blocker for people with PHP < 5.5

**Comment by h4kuna** [comment]
Today i will fix it.

**Comment by h4kuna** [comment]
Try update Ares to 1.0.7.

**Comment by h4kuna** [comment]
ping @DigitalSolutionsCZ
